  
send_command:
  description: Send device command through Cover.
  fields:
    command: {description: The command to be sent., example: 'open_cover'}
    device_id: {description: device ID.}
set_known_position:
  description: Set position aquired outside of this component without triggering action
  fields:
    entity_id:
      description: entity id of cover to set position for
      example: cover.garage_door
    position:
      description: position of cover, between 0 and 100
      example: 50
    confident:
      description: optional (default is false) - if we are confident in this position, i.e. affects if state is assumed or not
      example: True
    position_type:
      description: optional (default is target)- specifies if the position we are passing in is the target or the current position. Defaults to target meaning we will transition slider from current posution to given target. Specifiying current will set current position.
      example: current

